Update system-tests.yml

diff --git a/.github/workflows/system-tests.yml b/.github/workflows/system-tests.yml
--- a/.github/workflows/system-tests.yml
+++ b/.github/workflows/system-tests.yml
@@ -22,7 +22,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
     - name: Checkout source
       uses: actions/checkout@v2.5.0
@@ -33,32 +33,32 @@ jobs:
       uses: actions/setup-dotnet@v2.1.1
       with:
         dotnet-version: '7.0.x'
-      
-    #- name: Run System Tests
-      #id: test
-      #run: dotnet test ${{ inputs.project_test_file_path }} --filter Category="System.Tests" --results-directory ./TestResults --logger "trx;LogFileName=system-tests-results.trx"
 
-    - name: Failing step
+    - name: Run System Tests
       id: test
-      run: exit 1
+      run: dotnet test ${{ inputs.project_test_file_path }} --filter Category="System.Tests" --results-directory ./TestResults --logger "trx;LogFileName=system-tests-results.trx"
 
-    - name: Login to Jira
-      uses: atlassian/gajira-login@master
-      if: failure()
-      env:
-        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
-        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
-        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
+    #- name: Failing step
+      #id: test
+      #run: exit 1
 
-    - name: Create Jira issue on job failure
-      uses: atlassian/gajira-create@master
-      if: failure()
-      with:
-        project: NWL
-        issuetype: "Bug"
-        summary: "System Tests failed for ${{ github.repository }}"
-        description: "Created from GitHub Action"
-        fields: '{"customfield_10031": {id: "10021"}}'
+    #- name: Login to Jira
+      #uses: atlassian/gajira-login@master
+      #if: failure()
+      #env:
+        #JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
+        #JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
+        #JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
+
+    #- name: Create Jira issue on job failure
+      #uses: atlassian/gajira-create@master
+      #if: failure()
+      #with:
+        #project: NWL
+        #issuetype: "Bug"
+        #summary: "System Tests failed for ${{ github.repository }}"
+        #description: "Created from GitHub Action"
+        #fields: '{"customfield_10031": {id: "10021"}}'
 
     - name: Upload System Tests Results
       uses: dorny/test-reporter@v1.6.0
